#!/bin/sh

print_help() {
    cat <<EOF
usage: $0 [URL] [OUTPUT] [RATIO]
positional args:
  \$1 - URL    (required) 
  \$2 - OUTPUT (default: '%(title)s')
  \$3 - RATIO  (default: 1.35)
EOF
}

if [ -z "$1" ]; then
    print_help
    exit 0
fi

case $1 in
-h)
    print_help
    exit 0
    ;;
esac

output="$2"
[ -n "$output" ] || output="%(title)s"
ratio="$3"
[ -n "$ratio" ] || ratio="1.35"

yt-dlp "$1" -f "bestaudio/best" -o "$output.%(ext)s" -R infinite --exec "ffmpeg -i '$output.%(ext)s' -filter:a atempo='$ratio' '${output}x${ratio}.%(ext)s'"
