#!/bin/sh

CRONTAB_BAK="$HOME/crontab.bak"
CRONTAB_BAK_OLD="$CRONTAB_BAK.old"

crons="$(crontab -l 2>/dev/null)"

if [ ! -f "$CRONTAB_BAK" ]; then
	case $crons in
	"no crontab"*) ;;
	*)
		echo "$crons" >"$CRONTAB_BAK"
		crontab -r
		;;
	esac
else
	crontab <"$CRONTAB_BAK"
	mv "$CRONTAB_BAK" "$CRONTAB_BAK_OLD"
fi
