#!/bin/sh

start_mpd() {
    mpd
}

if ! pidof mpd >/dev/null; then
    if ! start_mpd && [ -z "$(pidof mpd)" ]; then
        notify-send -a mpd-toggle "can't start mpd"
    else
        notify-send -a mpd-toggle 'mpd started'
    fi
else
    killall mpd && notify-send -a mpd-toggle 'mpd killed'
fi
