#!/bin/sh

start_mpd() {
    mpd
}

notify() { [ -n "$1" ] && notify-send -i mpd -a "$(basename "$0")" "$1"; }

if ! pidof mpd >/dev/null; then
    if ! start_mpd && [ -z "$(pidof mpd)" ]; then
        notify "can't start mpd"
    else
        notify 'mpd started'
    fi
else
    killall mpd && notify 'mpd killed'
fi
