#!/bin/sh

err_msg() {
    notify-send -i newsboat -a "$(basename "$0")" "$1"
    exit 1
}

[ -n "$1" ] || err_msg "no input url"

FEED_URL="$1"
DB_FILE="${XDG_DATA_HOME:-$HOME/.local/share}/newsboat/cache.db"
COUNT_TO_LEAVE=15

[ -f "$DB_FILE" ] || err_msg "Database file '$DB_FILE' not exists"

if [ -z "$(sqlite3 <. -init /dev/null -column "$DB_FILE" "SELECT feedurl FROM rss_item WHERE feedurl = '$FEED_URL';")" ]; then
    err_msg "No such feed url in db: '$FEED_URL'"
fi

trap 'exit 0' INT
printf "Mark as deleted all except last (default: %d): " "$COUNT_TO_LEAVE"
read -r answ_count
if [ -n "$answ_count" ]; then
    echo "$answ_count" | grep -qP '^(0|[1-9]\d*)$' || err_msg "invalid count '$answ_count'"
    COUNT_TO_LEAVE=$((answ_count))
fi

count=$(($(sqlite3 <. -init /dev/null -column "$DB_FILE" "SELECT COUNT(*) FROM rss_item WHERE feedurl = '$FEED_URL';")))
if [ $count -gt $COUNT_TO_LEAVE ]; then
    query="UPDATE rss_item SET deleted = 1 WHERE feedurl = '$FEED_URL' AND id NOT IN \
        (SELECT id FROM rss_item WHERE feedurl = '$FEED_URL' ORDER BY pubDate DESC LIMIT $COUNT_TO_LEAVE);"
    printf '%s\n\nexecute it? [y/N]: ' "$query"
    read -r answ_exec
    case $answ_exec in
    [yY]*) sqlite3 <. -init /dev/null "$DB_FILE" "$query" ;;
    esac
fi
