#!/bin/sh

if [ -z "$1" ]; then
    notify-send -i newsboat -a "$(basename "$0")" "$1"
    exit 1
fi

setsid -f alacritty --class RadioTerm --config-file "${XDG_CONFIG_HOME}/alacritty/radio.toml" \
    -e sh -c "mpv $1 --no-vid --ytdl-raw-options=retries=infinite; read -r _"
