#!/bin/sh

# shellcheck disable=SC2086

url="$1"
if [ -z "$url" ]; then
    echo "url not passed"
    exit 1
fi

DEFAULT_FORMAT=b/bv+ba
DEFAULT_OUTPUT="$HOME/Videos/YouTube/%(uploader)s/%(title)s.%(ext)s"
if echo "$url" |
    grep -qP '^(?:https\:\/\/)?(?:www\.)?(youtube\.com\/playlist\?list=[A-Za-z0-9\-_]{18,34})'; then
    DEFAULT_OUTPUT="$HOME/Videos/YouTube/%(uploader)s/%(playlist_title)s/%(playlist_index)d %(title)s.%(ext)s"
fi

yt-dlp -sF -I:1 "$url"

print_questions() {
    cat <<EOF
format choose format (default: '$DEFAULT_FORMAT'):
output choose output (t for title, default: '$DEFAULT_OUTPUT'):
opts extra yt-dlp options (default: ''):
tsp run with tsp? (y/N):
EOF
}

if command -v rlwrap >/dev/null 2>&1; then
    ask_question() { rlwrap -S "$1 " -e '' -C nb-ytdl-dialog -o cat; }
else
    ask_question() {
        printf '%s' "$1 "
        read -r answ
        printf '%s' "$answ"
    }
fi

format=
output=
ytdlp_opts=
use_tsp=
questions_count=$(print_questions | wc -l)
i=1
while :; do
    line=$(print_questions | head -n $i | tail -n 1)
    type_="${line%% *}"
    question="${line#* }"
    case $type_ in
    format) format=$(ask_question "$question") ;;
    output) output="$(ask_question "$question")" ;;
    opts) ytdlp_opts="$(ask_question "$question")" ;;
    tsp) use_tsp="$(ask_question "$question")" ;;
    *) exit 1 ;;
    esac
    i=$((i + 1))
    [ $i -gt "$questions_count" ] && break
done

[ -n "$format" ] || format="$DEFAULT_FORMAT"
if [ -z "$output" ]; then
    output="$DEFAULT_OUTPUT"
else
    case $output in
    t) output="%(title)s.%(ext)s" ;;
    esac
fi

case $use_tsp in
y)
    notify-send -i newsboat -a newsboat "⬇️Start downloading '$url'..."
    qid="$(tsp yt-dlp "$url" -f "$format" -o "$output" $ytdlp_opts)"
    tsp -D "$qid" notify-send -i newsboat -a newsboat "✅Download done: '$url'" >/dev/null
    ;;
*)
    yt-dlp "$url" -f "$format" -o "$output" $ytdlp_opts
    ;;
esac
