#!/bin/sh

[ -n "$1" ] || exit 1
url="$1"

: "${OUTPUT=$HOME/Music/Podcasts/%(uploader)s/%(title)s}"

notify-send -i newsboat -a newsboat "⬇️Start downloading '$url'..."
qid=$(tsp yt-dlp "$url" -f ba -o "${OUTPUT}.%(ext)s" \
    --exec "ffmpeg -hide_banner -i '${OUTPUT}.%(ext)s' -vn -filter:a atempo=1.35 '${OUTPUT}x1.35.%(ext)s'")
tsp -D "$qid" notify-send -i newsboat -a newsboat "✅Download done: '$url'"
