#!/bin/sh

[ -n "$1" ] || exit 1
url="$1"

DEFAULT_FORMAT="b"
DEFAULT_OUTPUT="$HOME/Videos/YouTube/%(uploader)s/%(title)s.%(ext)s"

yt-dlp -F "$url"

printf 'choose format (default: '%s'): ' "$DEFAULT_FORMAT"
read -r format
[ -n "$format" ] || format="$DEFAULT_FORMAT"

printf 'choose output (default: '%s'): ' "$DEFAULT_OUTPUT"
read -r out
[ -n "$out" ] || out="$DEFAULT_OUTPUT"

notify-send -i newsboat -a newsboat "⬇️Start downloading '$url'..."
qid="$(tsp yt-dlp "$url" -f "$format" -o "$out")"
tsp -D "$qid" notify-send -i newsboat -a newsboat "✅Download done: '$url'"
