#!/bin/sh

# shellcheck disable=SC2086

url="$1"
if [ -z "$url" ]; then
    echo "url not passed"
    exit 1
fi

DEFAULT_FORMAT=b/bv+ba
DEFAULT_OUTPUT="$HOME/Videos/YouTube/%(uploader)s/%(title)s.%(ext)s"
if echo "$url" |
    grep -qP '^(?:https\:\/\/)?(?:www\.)?(youtube\.com\/playlist\?list=[A-Za-z0-9\-_]{18,34})'; then
    DEFAULT_OUTPUT="$HOME/Videos/YouTube/%(uploader)s/%(playlist_title)s/%(playlist_index)d %(title)s.%(ext)s"
    yt-dlp -sF -I :1 "$url"
else
    yt-dlp -F "$url"
fi

printf "choose format (default: '%s'): " "$DEFAULT_FORMAT"
read -r format
[ -n "$format" ] || format="$DEFAULT_FORMAT"

printf "choose output (t for title, default: '%s'): " "$DEFAULT_OUTPUT"
read -r out
[ -n "$out" ] || out="$DEFAULT_OUTPUT"
case $out in
t) out="%(title)s.%(ext)s" ;;
esac

ytdlp_opts=
printf "extra yt-dlp options (default: '%s'): " "$ytdlp_opts"
read -r extra_ytdlp_opts
[ -n "$extra_ytdlp_opts" ] && ytdlp_opts="${ytdlp_opts} ${extra_ytdlp_opts}"

printf 'run with tsp? (y/N): '
read -r use_tsp
case $use_tsp in
y)
    notify-send -i newsboat -a newsboat "⬇️Start downloading '$url'..."
    qid="$(tsp yt-dlp "$url" -f "$format" -o "$out" $ytdlp_opts)"
    tsp -D "$qid" notify-send -i newsboat -a newsboat "✅Download done: '$url'" >/dev/null
    ;;
*)
    yt-dlp "$url" -f "$format" -o "$out" $ytdlp_opts
    ;;
esac
