#!/bin/sh

: "${C_FZF_CMD:=fzf --preview= --delimiter=\/ --with-nth=-1}"
: "${C_EDITOR_CMD:=$EDITOR}"

if [ -z "$C_EDITOR_CMD" ]; then
    echo 'C_EDITOR_CMD and EDITOR variables are not set'
    exit 1
fi

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"
if [ ! -d "$CONFIG_DIR" ]; then
    echo "config dir '$CONFIG_DIR' not found"
    exit 1
fi

inp=
if [ -n "$1" ]; then
    inp="$1"
elif [ ! -t 0 ]; then
    while read -r line; do
        inp="${inp}$line"
    done
fi

[ -n "$inp" ] && set -- -q "$inp"
set -- --header='ctrl-z: execute zc' --bind='ctrl-z:execute(zc)+abort'
choice="$(find -L "$CONFIG_DIR" -maxdepth 1 |
    grep -v "^$CONFIG_DIR$" | $C_FZF_CMD "$@")"

[ -n "$choice" ] || exit 0

is_single_file_() {
    if [ -d "$choice" ]; then
        set -- "$choice"/* 2>/dev/null
        [ $# -eq 1 ] && echo "$1"
    fi
}
single_file_="$(is_single_file_)"
[ -f "$single_file_" ] && choice="$single_file_"

eval "$C_EDITOR_CMD $choice"
