#!/bin/sh

: "${C_FZF_CMD:=fzf --preview=}"

: "${CONFIG_EDITOR:=$EDITOR}"
if [ -z "$CONFIG_EDITOR" ]; then
    echo 'CONFIG_EDITOR and EDITOR variables are not set'
    exit 1
fi

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"
if [ ! -d "$CONFIG_DIR" ]; then
    echo "config dir '$CONFIG_DIR' not found"
    exit 1
fi

inp=
if [ -n "$1" ]; then
    inp="$1"
elif [ ! -t 0 ]; then
    while read -r line; do
        inp="${inp}$line"
    done
fi

[ -n "$inp" ] && set -- -q "$inp"

choice="$(find -L "$CONFIG_DIR" -maxdepth 1 -printf '%f\n' |
    grep -P '^[^\.].+$' | $C_FZF_CMD "$@")"

[ -n "$choice" ] || exit 0

is_single_file_() {
    set -- "$CONFIG_DIR/$choice"/* 2>/dev/null
    [ $# -eq 1 ] && echo "$1"
}
single_file_="$(is_single_file_)"
if [ -f "$single_file_" ]; then
    "$CONFIG_EDITOR" "$single_file_"
else
    "$CONFIG_EDITOR" "$CONFIG_DIR/$choice"
fi
