#!/bin/sh

config_editor="${CONFIG_EDITOR:-$EDITOR}"
if [ -z "$config_editor" ]; then
    echo "CONFIG_EDITOR and EDITOR variables are not set"
    exit 1
fi

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"
if [ ! -d "$CONFIG_DIR" ]; then
    echo "config dir '$CONFIG_DIR' not found"
    exit 1
fi

choosed_dir="$(find "$CONFIG_DIR" -maxdepth 1 -type d -printf '%f\n' | grep -P '^[^\.].+$' | fzf)"

if [ -z "$choosed_dir" ]; then
    exit 0
fi

if [ ! -d "$CONFIG_DIR/$choosed_dir" ]; then
    echo "choosed dir '$choosed_dir' not found"
    exit 1
fi

"$config_editor" "$CONFIG_DIR/$choosed_dir"
