#!/bin/sh

C_FZF_CMD="${C_FZF_CMD:=fzf --preview=}"
C_EDITOR_CMD="${C_EDITOR_CMD:-$EDITOR}"
if [ -z "$C_EDITOR_CMD" ]; then
    echo "C_EDITOR_CMD and EDITOR variables are not set"
    exit 1
fi

choice="$(find -L "$ZDOTDIR" -maxdepth 1 -type f  -printf '%f\n' |
    grep -P '^[^\.].+$' | $C_FZF_CMD)"
[ -n "$choice" ] || choice=.zshrc

eval "$C_EDITOR_CMD $ZDOTDIR/$choice"
