#!/bin/sh

show_help() {
    cat <<EOF
Usage: $0 [-e CONFIG_SECTION]

Options:
  -e  edit given config file ([a]liases | [ab]breviations | [b]indings | [p]rofile | [w]idgets)
  -h  show this message
EOF
}

config_section=""

parse_args() {
    OPTIND=1
    while getopts "he:" opt; do
        case "$opt" in
        h)
            show_help
            exit 0
            ;;
        e) config_section=$OPTARG ;;
        *)
            show_help
            exit 1
            ;;
        esac
    done

    shift $((OPTIND - 1))
    [ "${1:-}" = "--" ] && shift
}

parse_args "$@"

config_editor="${CONFIG_EDITOR:-$EDITOR}"
if [ -z "$config_editor" ]; then
    echo "CONFIG_EDITOR and EDITOR variables are not set"
    exit 1
fi

file_to_edit="$ZDOTDIR/.zshrc"

case $config_section in
ab) file_to_edit="$ZDOTDIR/abbreviations" ;;
a) file_to_edit="$ZDOTDIR/aliases" ;;
b) file_to_edit="$ZDOTDIR/bindings" ;;
p) file_to_edit="$ZDOTDIR/profile" ;;
w) file_to_edit="$ZDOTDIR/widgets" ;;
esac

"$config_editor" "$file_to_edit"
